name: 'NPM publish'
description: 'This action publishes a package to the npm registry.'

inputs:
  token:
    description: 'The npm token to use for authentication.'
    required: true
  is_beta:
    description: 'A stringified boolean indicating whether to publish the package as a beta version.'
    required: false
    default: 'false'

outputs:
  artifact_filepath:
    description: 'The path to the published package artifact.'
    value: ${{ steps.npm_publish.outputs.artifact_filepath }}

runs:
  using: composite
  steps:
    - name: NPM publish
      id: npm_publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        artifact_filepath=$(pwd)/$(npm pack --json | jq -r '.[0].filename')
        echo "artifact_filepath=$artifact_filepath" >> "$GITHUB_OUTPUT"

        release_cmd="npm publish --access public"
        if [ "${{ inputs.is_beta }}" = 'true' ]; then
          release_cmd="$release_cmd --tag beta"
        fi

        $release_cmd
