name: NPM publish
description: 'This action publishes a package to the npm registry.'

inputs:
  token:
    description: 'The npm token to use for authentication.'
    required: true
  is_beta:
    description: 'A stringified boolean indicating whether to publish the package as a beta version.'
    required: false
    default: 'false'
  use_pnpm:
    description: 'A stringified boolean indicating whether to use pnpm for publishing.'
    required: false
    default: 'false'

outputs:
  artifact_filepath:
    description: 'The path to the published package artifact.'
    value: ${{ steps.npm_publish.outputs.artifact_filepath }}

runs:
  using: composite
  steps:
    - name: NPM publish
      id: npm_publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        IS_BETA: ${{ inputs.is_beta }}
      shell: bash
      run: |
        pkg_mngr=$(if [ "${{ inputs.use_pnpm }}" = 'true' ]; then echo 'pnpm'; else echo 'npm'; fi)

        artifact_filepath=$(pwd)/$($pkg_mngr pack --json | jq -r '.[0].filename')
        echo "artifact_filepath=$artifact_filepath" >> "$GITHUB_OUTPUT"

        release_cmd="$pkg_mngr publish --access public"
        if [ "$IS_BETA" = 'true' ]; then
          release_cmd="$release_cmd --tag beta"
        fi

        $release_cmd
