name: NPM publish
description: 'This action publishes a package to the npm registry.'

inputs:
  token:
    description: 'The npm token to use for authentication.'
    required: false
  is_beta:
    description: 'A stringified boolean indicating whether to publish the package as a beta version.'
    required: false
    default: 'false'
  package_manager:
    description: 'The package manager to use for publishing.'
    required: false
    default: 'npm'
  enable_provenance:
    description: 'Enable package provenance.'
    required: false
    default: 'true'


outputs:
  artifact_filepath:
    description: 'The path to the published package artifact.'
    value: ${{ steps.npm_publish.outputs.artifact_filepath }}

runs:
  using: composite
  steps:
    - name: NPM publish
      id: npm_publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        IS_BETA: ${{ inputs.is_beta }}
        NPM_CONFIG_PROVENANCE: ${{ inputs.enable_provenance }}
      shell: bash
      run: |
        artifact_filepath=$(pwd)/$(${{ inputs.package_manager }} pack --json | jq -r '.[0].filename')
        echo "artifact_filepath=$artifact_filepath" >> "$GITHUB_OUTPUT"

        release_cmd="${{ inputs.package_manager }} publish --access public"
        if [ "$IS_BETA" = 'true' ]; then
          release_cmd="$release_cmd --tag beta"
        fi

        $release_cmd
