name: Generate release notes
description: "This action generates release notes based on the repository's commit messages written according to the Conventional Commits specification."

inputs:
  file_name:
    description: 'The name of the file to write the release notes to.'
    required: false
    default: 'RELEASE_NOTES.md'

  version:
    description: 'The release version to generate release notes for.'
    required: false
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Generate changelog
      shell: bash
      env:
        FILE_NAME: ${{ inputs.file_name }}
        VERSION: ${{ inputs.version }}
      run: cz changelog "$VERSION" --file-name="$FILE_NAME"
