name: Check pull request title
description: 'This action checks the title of a pull request to ensure it follows the Conventional Commits specification.'

inputs:
  include_description:
    description: 'Include the pull request description in the commit message.'
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Check pull request title
      shell: bash
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
      run: |
        echo $PR_TITLE > commit-message.txt

        if [ "${{ inputs.include_description }}" == "true" ]; then
          echo -e "\n\n${PR_DESCRIPTION}" >> commit-message.txt
        fi

        cz check --commit-msg-file commit-message.txt
