name: 'Check pull request title'
description: 'This action checks the title of a pull request to ensure it follows the Conventional Commits specification.'

runs:
  using: composite
  steps:
    - name: 'Check pull request title'
      shell: bash
      run: cz check -m "${{ github.event.pull_request.title }}"
