name: 'Generate changelog'
description: "This action generates changelog based on the repository's commit messages written according to the Conventional Commits specification."

inputs:
  file_name:
    description: 'The name of the file to write the changelog to.'
    required: false
    default: 'CHANGELOG.md'

runs:
  using: composite
  steps:
    - name: 'Generate changelog'
      shell: bash
      env:
        FILE_NAME: ${{ inputs.file_name }}
      run: cz changelog --incremental --merge-prerelease --file-name="$FILE_NAME"
