name: 'Setup pnpm'
description: 'This action sets up [pnpm](https://pnpm.io/) for use in actions.'

inputs:
  node_version_file:
    description: 'Set a node version file to determine the Node.js version to use'
    required: false
    default: .node-version

  node_version:
    description: 'Set a specific Node.js version to use'
    required: false
    default: ''

  working_directory:
    description: 'The directory to run pnpm commands in'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v3
      with:
        package_json_file: ${{ inputs.working_directory }}/package.json

    - name: 'Calculate node version file path'
      shell: bash
      id: node-version-file-path
      # If `node_version_file` is the default `.node-version`, we need to prepend the working directory to the path
      run: |
        if [ "${{ inputs.node_version_file }}" = ".node-version" ]; then
          echo "path=${{ inputs.working_directory }}/${{ inputs.node_version_file }}" >> $GITHUB_OUTPUT
        else
          echo "path=${{ inputs.node_version_file }}" >> $GITHUB_OUTPUT
        fi

    - name: 'Install Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        node-version-file: ${{ steps.node-version-file-path.outputs.path }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
        cache-dependency-path: ${{ inputs.working_directory }}/pnpm-lock.yaml

    - name: 'Install dependencies'
      shell: bash
      run: pnpm i --frozen-lockfile
      working-directory: ${{ inputs.working_directory }}
