name: 'Setup pnpm'
description: 'This action sets up [pnpm](https://pnpm.io/) for use in actions.'

inputs:
  node_version_file:
    description: 'Set a node version file to determine the Node.js version to use'
    required: false
    default: .node-version

  node_version:
    description: 'Set a specific Node.js version to use'
    required: false
    default: ''

  working-directory:
    description: 'The directory to run pnpm commands in'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v3
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json

    - name: 'Install Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        node-version-file: ${{ inputs.node_version_file }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: 'Install dependencies'
      shell: bash
      run: pnpm i --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}
