name: Setup pnpm
description: 'This action sets up [pnpm](https://pnpm.io/) for use in actions.'

inputs:
  node_version_file:
    description: 'Set a node version file to determine the Node.js version to use'
    required: false
    default: .node-version

  node_version:
    description: 'Set a specific Node.js version to use'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node_version }}
        node-version-file: ${{ inputs.node_version_file }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
