name: 'Check commit messages workflow'
description: 'This workflow generates a changelog and creates a pull request to update the repository.'

on:
  workflow_call:
    inputs:
      starting_commit:
        description: 'The commit to start checking from.'
        required: false
        default: '${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}'

jobs:
  check_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Python'
        uses: dfinity/ci-tools/actions/setup-python@main

      - name: 'Setup Commitizen'
        uses: dfinity/ci-tools/actions/setup-commitizen@main

      - name: 'Check commit messages'
        uses: dfinity/ci-tools/actions/check-commit-messages@main
        with:
          starting_commit: ${{ inputs.starting_commit }}
