name: 'Setup Python'
description: 'This action sets up Python and pip for use in actions.'

runs:
  using: 'composite'
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 'Install PIP'
      shell: bash
      run: python -m pip install --upgrade pip
