name: 'Approve pull request'
description: 'This action approves a pull request and optionally enables automerge.'
author: 'DFINITY Stiftung'

inputs:
  pull_request_number:
    description: 'Pull request number to approve.'
    required: true
  auto_merge:
    description: 'Enable auto-merge for the pull request.'
    required: false
    default: false
  token:
    description: 'Access token to manage the pull request.'
    required: false
    default: ${{ github.token }}
  merge_method:
    description: 'Merge method to use when auto-merging. Supported values are "merge", "squash", and "rebase".'
    required: false
    default: 'merge'

runs:
  using: node20
  main: dist/index.js
