name: 'Check commit messages'
description: 'This action checks the commit messages on a branch to ensure they follow the Conventional Commits specification.'

inputs:
  target_branch:
    description: 'The branch to check against. All commits on the current branch that are not on the target branch will be checked.'
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - name: 'Check commit messages'
      shell: bash
      run: cz check --rev-range origin/${{ inputs.target_branch }}..HEAD
