name: Check PR title workflow

on:
  workflow_call:

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: dfinity/ci-tools/actions/setup-python@059c18686a7318d8b67fb361bc2d939b16b3959f # main

      - name: Setup Commitizen
        uses: dfinity/ci-tools/actions/setup-commitizen@059c18686a7318d8b67fb361bc2d939b16b3959f # main

      - name: Check pull request title
        uses: dfinity/ci-tools/actions/check-pr-title@059c18686a7318d8b67fb361bc2d939b16b3959f # main
