name: Check PR title workflow

on:
  workflow_call:

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: dfinity/ci-tools/actions/setup-python@28f8eefc873d714eed3de4c1b79375cce6b93d46 # main

      - name: Setup Commitizen
        uses: dfinity/ci-tools/actions/setup-commitizen@28f8eefc873d714eed3de4c1b79375cce6b93d46 # main

      - name: Check pull request title
        uses: dfinity/ci-tools/actions/check-pr-title@28f8eefc873d714eed3de4c1b79375cce6b93d46 # main
