name: Check PR title workflow

on:
  workflow_call:

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: dfinity/ci-tools/actions/setup-python@4b4a84c58faa93db27c778a898e5a941948b3511 # main

      - name: Setup Commitizen
        uses: dfinity/ci-tools/actions/setup-commitizen@4b4a84c58faa93db27c778a898e5a941948b3511 # main

      - name: Check pull request title
        uses: dfinity/ci-tools/actions/check-pr-title@4b4a84c58faa93db27c778a898e5a941948b3511 # main
