name: 'Check PR title workflow'

on:
  workflow_call:

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Python'
        uses: dfinity/ci-tools/actions/setup-python@main

      - name: 'Setup Commitizen'
        uses: dfinity/ci-tools/actions/setup-commitizen@main

      - name: 'Check pull request title'
        uses: dfinity/ci-tools/actions/check-pr-title@main
