name: 'Generate changelog workflow'

on:
  workflow_call:
    inputs:
      file_name:
        description: 'The name of the file to write the changelog to.'
        required: false
        default: 'CHANGELOG.md'
        type: string

      branch_name:
        description: 'The name of the branch to create the pull request from.'
        required: false
        default: 'chore/generate-changelog'
        type: string
      base_branch_name:
        description: 'The name of the base branch to create the pull request against.'
        required: false
        default: 'main'
        type: string

      pull_request_title:
        description: 'The title of the pull request.'
        required: false
        default: 'chore: generate changelog'
        type: string
      pull_request_body:
        description: 'The body of the pull request.'
        required: false
        default: 'This pull request was automatically created by a GitHub Action to generate changelogs.'
        type: string

      author_name:
        description: 'The name of the author of the pull request and commit.'
        required: false
        default: '${{ github.actor }}'
        type: string
      author_email:
        description: 'The email of the author of the pull request and commit.'
        required: false
        default: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
        type: string

      commit_message:
        description: 'The message of the commit.'
        required: false
        default: 'chore: generate changelog'
        type: string

      token_app_id:
        description: 'A GitHub App ID used to generate an access token to create a pull request.'
        required: true
        type: string

    secrets:
      token_private_key:
        description: 'A GitHub App private key used to generate an access token to create a pull request.'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create GitHub App Token'
        uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: ${{ inputs.token_app_id }}
          private-key: ${{ secrets.token_private_key }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Python'
        uses: dfinity/ci-tools/actions/setup-python@main

      - name: 'Setup Commitizen'
        uses: dfinity/ci-tools/actions/setup-commitizen@main

      - name: 'Generate changelog'
        uses: dfinity/ci-tools/actions/generate-changelog@main
        with:
          file_name: ${{ inputs.file_name }}

      - name: 'Create pull request'
        uses: dfinity/ci-tools/actions/create-pr@main
        with:
          branch_name: ${{ inputs.branch_name }}
          base_branch_name: ${{ inputs.base_branch_name }}
          pull_request_title: ${{ inputs.pull_request_title }}
          pull_request_body: ${{ inputs.pull_request_body }}
          author_name: ${{ inputs.author_name }}
          author_email: ${{ inputs.author_email }}
          commit_message: ${{ inputs.commit_message }}
          token: ${{ steps.generate_token.outputs.token }}
