name: Check Transpiled JavaScript

on:
  merge_group:
  pull_request:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check_dist:
    name: check_dist:required
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action_name: ['create-pr', 'assemble-docs', 'submit-docs']
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PNPM
        uses: ./actions/setup-pnpm

      - name: Build @dfinity/action-utils
        run: pnpm -F @dfinity/action-utils build

      - name: Check ${{ matrix.action_name }} dist folder
        uses: ./.github/actions/check-dist
        with:
          action_name: ${{ matrix.action_name }}
